# Generated by Django 5.2.6 on 2025-11-29 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_alter_moviecategory_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviecategory',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
