# Generated by Django 5.2.6 on 2025-12-02 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_alter_moviecategory_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('studio', models.CharField(max_length=50)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('duration', models.PositiveIntegerField(blank=True, help_text='Duration in minutes', null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('director', models.CharField(blank=True, max_length=50, null=True)),
                ('language', models.CharField(blank=True, max_length=30, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='movie.moviecategory')),
            ],
        ),
    ]
